### ISSUE TITLE
Všude: "url" => "URL" nebo "IRI"

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#10]
Podle toho, zda očekáváme, že na daném URL něco bude (např. obrázek) nebo ne nutně (identifikátor) mluvíme o URL nebo IRI. Nikoliv "url" => je třeba mít jednotný styl.

**Comment by spalrobert** [comment]
kde myslíš? v jsonu nebo v  specifikaci? Našli sme v jsonu u tvojich OFN že používaš maleé iri a url. Jedine kde by sa to dalo upraviť je v popise v špecifikácii...

**Comment by jakubklimek** [comment]
V lidsky čitelných textech v HTML: 
![image](https://user-images.githubusercontent.com/718827/67012036-faad7600-f0f0-11e9-86c9-62b1be5fa147.png)

**Comment by jakubklimek** [comment]
@spalrobert U aktualit to pořád je:
![image](https://user-images.githubusercontent.com/718827/68924357-ed7fb780-0780-11ea-8986-b0a764921f60.png)
https://github.com/jirkamarekbrno/otevrene-formalni-normy/blob/master/aktuality/draft/index.html#L140

**Comment by spalrobert** [comment]
Prisahám že som to menil a nerozumiem tomu prečo to znova je malé. Už som to ale commitol.
