### ISSUE TITLE
Upravit Akce kvůli Vstupnému

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#16]
@spalrobert Je třeba akce upravit tak, aby použiívaly teď už separátní OFN Vstupné, tj.

- [x] Obrázek
- [x] Specifikaci
- [x] JSON schéma
- [x] JSON příklad
- [x] JSON příklad v HTML

**Comment by jirkamarekbrno** [comment]
Zkontrolováno a mělo by tam být vše, jak to má být. @jakubklimek prosím o uzavření issue

**Comment by jakubklimek** [comment]
Komplexní příklad akce je špatně.

- [ ] Není validní v [JSONLint](https://jsonlint.com/)
- [ ] V názvaznosti na #43 :
  - zvážit, zda je třeba v příkladu akce mít rozpad vstupného i na časovou platnost - mně to přijde zbytečné
  - pokud je to ale důležité, pak je časová platnost v příkladu špatně
    - má přímo začátek a konec, což ale v [OFN](https://ofn.gov.cz/časová-platnost/draft/) tak není - tam to je ještě přes `časový_interval` nebo `časová_opakovatelnost`
  - link ze specifikace ve Vstupném vede na https://ofn.gov.cz/základní-datové-typy/draft/#časová-platnost místo do časové platnosti

**Comment by spalrobert** [comment]
komplexný json príklad nie je validný kvoli dublovaniu osoby v sponzorovi? Ako to odstránim? dal som osoba1 a validátor potom píše že OK. Ako to myslíš s tou časovou platnosťou? Akože v príklade zostane iba názov a podmínka vstupného? Alebo by to tam zostalo prázdné ako je to u vstupného až kým sa nevyrieši tá ofn časová platnost?

**Comment by spalrobert** [comment]
Aký link kde myslíš? Neviem to nájsť. Nerozumiem... v špecifikácii akce - vstupné nič také nie je.

**Comment by spalrobert** [comment]
Čo sa táka specifikace časovej platnosti ve vstupném tak som tam zatiaľ dal link na zákl. datové typy pretože tá platnosť ešte nemá ofn. Mám to prehodiť na časový inteval?

**Comment by jakubklimek** [comment]
Hlavně se u toho validátoru nespoléhejte na to, že když to nehlásí chybu, tak je to OK. Takhle 100% to neni. On kontroluje stylem "kdyz je tam neco, co se jmenuje jako ve schematu, pak to musi splnovat to co je ve schematu", cili kdyz tam date neco jinyho, tak se to nevaliduje. Dále například když máte blbě schéma (schválně si ho zvalidujte v jsonlintu), pak je validní kde co. Musíte zkusit rozbít nějaký datový typ (třeba někde dát číslo místo stringu apod.) a když to správně zařve, pak je to OK. Když to nezařve, tak to nevaliduje dobře.

Kdyz to udelate, tak si vsimnete, ze neni validni ani https://ofn.gov.cz/vstupné/draft/schémata/vstupné.json

> Ako to myslíš s tou časovou platnosťou? Akože v príklade zostane iba názov a podmínka vstupného?

Ano. Nicméně teď už tu platnost máte, tak ji muzete pouzit.

> Čo sa táka specifikace časovej platnosti ve vstupném tak som tam zatiaľ dal link na zákl. datové typy pretože tá platnosť ešte nemá ofn.

@spalrobert vzdyt @jirkamarekbrno udelal https://ofn.gov.cz/časová-platnost/draft/#úvod - takze uz to lze pouzit (nerikam ze se to nebude upraovat).

**Comment by jakubklimek** [comment]
OK, nicméně souvisí s #56
