### ISSUE TITLE
Sportoviště: Kontaktů by mělo být možno mít více - každý pro jiný účel

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#19]
Tohle asi platí obecně, že kdykoliv je někde kontakt, mělo by být možné jich mít více pro různé účely.

**Comment by jirkamarekbrno** [comment]
@jakubklimek hotovo. Prosím o uzavření issues. Zkontrolování kontkatů i u jiných ofn jsem si zapsal do to do listu pro konsolidaci těch našich OFN. Děkuji. J
