### ISSUE TITLE
Sportoviště a turistické cíle: Definice vstupného

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#21]
@spalrobert Definice vstupného ve sportovišti je moc deskriptivní, tj. to co je a co není ve vstupném by zde nemělo být psáno, to je v OFN Vstupné. Tady by mělo být jen to, že se jedná o specifikaci vstupného.
![image](https://user-images.githubusercontent.com/718827/68925817-49980b00-0784-11ea-8ea6-89b13f68a965.png)

**Comment by jirkamarekbrno** [comment]
@jakubklimek opraveno ve sportovišti i v turistických cílech. Prosím o uzavření issue. Děkuji.
