### ISSUE TITLE
Všechny: pořadí vazeb

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#22]
Pořadí vazeb ve specifikaci by mělo odpovídat pořadí na obrázku. Je jedno kde se začne, ale pak bych očekával, že to bude ve stejnem pořadí.

**Comment by jirkamarekbrno** [comment]
@jakubklimek toto je problém všech našich OFN jsem zjistil. V rámci jejich konsolidace, to jednotně předěláme.

**Comment by jirkamarekbrno** [comment]
@jakubklimek toto udělal @spalrobert v rámci konsolidace #55 . Navrhuji uzavřít po pondělním merge tuto issue.
