### ISSUE TITLE
Sportoviště: zarovnat krabičky v obrázku

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#23]
Bezbariérovost vyčnívá :)

**Comment by jirkamarekbrno** [comment]
@jakubklimek hotovo:). udělal jsem to s commit #19 . Prosím o uzavření issue. Obecně ty obrázky budeme muset ještě sjednotit - to uděláme v rámci konsolidace. Děkuji. J
