### ISSUE TITLE
Sportoviště: doplňkové služby, sport, typ sportoviště -vícejazyčnost

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#24]
Ať už to budou číselníky nebo text, musí být podopora pro vícejazyčnost. Tj teď každopádně Text.

V příkladu to tak i je, ale ve specifikaci je Řetězec.

**Comment by jirkamarekbrno** [comment]
@jakubklimek opraveno, prosím o uzavření issue. Děkuji.

**Comment by jakubklimek** [comment]
Nyní to chybí v příkladech u otevírací doby.

**Comment by jirkamarekbrno** [comment]
@jakubklimek podle mě zde máme dvě issues na toto stejné. Ten tvůj poslední koment podle mě odkazuje na #50. Je tak? Pokud ano, prosím o uzvaření této issue. Děkuji. J
