### ISSUE TITLE
Turistické cíle: kouření

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#26]
Tady bych to trochu rozepsal na "kouření_povoleno", aby bylo jasnější, o co jde a že je to ano/ne.

Zároveň je třeba i v příkladu hodnoty dodržovat pravidla toho [datového typu](https://ofn.gov.cz/z%C3%A1kladn%C3%AD-datov%C3%A9-typy/draft/#boolean), tedy true/false, nikoliv Ano/Ne

**Comment by jakubklimek** [comment]
Ještě to není ono. V JSONu to má být
```json
"kouření_povoleno": true
```
a ne 
```json
"kouření_povoleno": "true"
```
https://www.jsonschemavalidator.net/ by to řekl (chybějící linkovaná schémata jako bezbariérovost a otevírací doba lze pro test vypustit)

![image](https://user-images.githubusercontent.com/718827/69635406-961cf980-1054-11ea-88ef-f5a69fe0634d.png)

**Comment by jirkamarekbrno** [comment]
@jakubklimek hotovo. Zkontrolováno. Je to na uzvaření issue. Díky.
