### ISSUE TITLE
Turistické cíle: kapacita

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#28]
Kapacita by měla být typu https://ofn.gov.cz/základní-datové-typy/draft/#množství

**Comment by jirkamarekbrno** [comment]
@jakubklimek toto je hotovo, prosím o uzavření issue. Děkuji.

**Comment by jakubklimek** [comment]
Příklad ve specifikaci je špatně, je tam stále 500, přitom množství musí mít jednotky. Konceptuální příklad tedy má být "500 lidí".

Příklad v JSONu je také špatně, taky je tam 500. Má tam být 500 lidí, strukturováno dle OFN základní datové typy - množství.

Opět to je vidět v https://www.jsonschemavalidator.net/

![image](https://user-images.githubusercontent.com/718827/69635883-abdeee80-1055-11ea-9268-bfafa52c6beb.png)

**Comment by jakubklimek** [comment]
Pořád je to v JSONu špatně. V [základních datových typech](https://ofn.gov.cz/základní-datové-typy/draft/#example-37-mnozstvi-v-json) je vidět, že to má být:
```json
"kapacita": {
    "hodnota": 500,
    "jednotka": "C62"
}
```

Ano, ty jednotky tady jsou trochu k zamyšlení, ale nic lepšího teď asi nemáme.

**Comment by jakubklimek** [comment]
Teď je to špatně ještě v HTML.
