### ISSUE TITLE
Turistické cíle: Jazyk

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#29]
Jazyk bude používat evropský číselník jazyků https://op.europa.eu/cs/web/eu-vocabularies/at-dataset/-/resource/dataset/language. Čili odkaz ze specifikace povede na toto URI, v příkladech pak budou použita IRI jednotlivých jazyků.

**Comment by jirkamarekbrno** [comment]
@jakubklimek prosím tě, mohl bys čeknout tuto issue, jestli je správně udělaná v turistických cílech? Abychom to mohli využít jako obecnou položku pro další ofn. Děkuji moc. Jirka

**Comment by jakubklimek** [comment]
- Jazyk by v obrázku měl být šedě - je to existující číselník, který nespecifikujeme
- Příklad je špatně, protože tam uvádítě IRI webové stránky v češtině o konkrétním jazyku (`https://op.europa.eu/cs/web/eu-vocabularies/at-concept/-/resource/authority/language/ARA/`). Správně tam musí být IRI toho konkrétního jazyku:
![image](https://user-images.githubusercontent.com/718827/69636093-1e4fce80-1056-11ea-91fb-5d8d0aaceafd.png)

Tedy `http://publications.europa.eu/resource/authority/language/ARA`

- V příkladu je to pak taky špatně (a v příkladu ve schématu)
  - špatné IRI viz výše
  - taky tam máte pole jazyků, ve kterém máte jeden objekt, který má 2 IRI. Mělo by to ale být pole IRI těch jazyků - tady už ten klíč `iri` je zbytečný. Takže:
```json
"jazyk": [
	"http://publications.europa.eu/resource/authority/language/BOS",
	"http://publications.europa.eu/resource/authority/language/ARA"
],
```
