### ISSUE TITLE
Akce: Časový interval u vstupného může být jen jeden. Je to tak OK?

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#3]
Aktuálně je vazba Vstupné - Časový interval n..1, takže jeden typ vstupného může platit pouze v jednom časovém intervalu. Je to tak ok, nebo by intervalů mělo být více?

**Comment by spalrobert** [comment]
V situácii že by vstupenka mala dva intervali napr. priatok až sobota a pondelok až streda tak to nedáva zmysel... to by boli už dve vstupenky. Určite je to možné takto vstupenku postaviť ale nikdy sme sa s tým v realite nestretli a nedáva nám to nejak zmysel. Ako ale vravím teoreticky je to možné avšak nikto to takto nerobí a preto sme tam dali 1.

**Comment by jakubklimek** [comment]
Co případ, kdy je akce, která má žádané dopoledne a méně žádané odpoledne, každý pracovní den? Tedy jedna týdenní vstupenka bude na každý všední den dopoledne, jiná na každý všední den odpoledne, třetí bude celodenní?
