### ISSUE TITLE
JSON Schéma: jednoduché datové typy

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#31]
Jednoduché datové typy v JSON schématech nemají vlastní JSON schéma soubor, definují se přímo v jazyce JSON Schéma. Tedy třeba booleovská hodnota u turistických cílů je špatně. Tam se použije type boolean.

**Comment by jirkamarekbrno** [comment]
@spalrobert musíme to upravit ještě v akcích a dalších. Jsem si všiml, že je toho víc, projdu to zítra vše.

**Comment by spalrobert** [comment]
Očekoval som si svoje akce, aktuality, vstupné a otevírací doba.

**Comment by dvoriik** [comment]
zkontrolováno i v rámci #55 ...mělo by být v pořádku :)
