### ISSUE TITLE
Vstupné: Úprava o minimalistický json príklad

### ISSUE THREAD

**Issue by spalrobert** [jirkamarekbrno/otevrene-formalni-normy#39]

**Comment by jirkamarekbrno** [comment]
@spalrobert toto je hotové ne?

**Comment by spalrobert** [comment]
malo by byť

**Comment by jakubklimek** [comment]
Z Issue mi není jasné, co se vlastně mělo dít. Nicméně příkald vstupného se stále jmenuje "Oznámení"

**Comment by spalrobert** [comment]
Myslím že pôvodne to bolo pridanie jednoduchého príkladu k vstupnému ale nakoniec po vytvorení som ho odstránil pretože bolo identické ako komplexné oznámení. Chybku som opravil a našiel som rovnakú aj v ofn akce tak je opravená aj tam. Nemali by sme tam nejak dať do html že min json pre aktuality tam nie je kvôli tomu že je identické s komplexným? aby to bolo pre čitateľa hneď jasné prečo to tam nie je a u ostatných je?

**Comment by jakubklimek** [comment]
@spalrobert Rikali jsme, ze pokdu je jen jeden, není třeba to dál komentovat. Nicméně:
1) teď se ten jediný příklad u vstupného jmenuje "Komplexní vstupné v JSON" - to je matoucí
2) Zrovna u vstupného bych čekal, že tam bude jak jednoduchý, tak komplexní. V jednoduchém rozhodně nepotřebuji tu časovou platnost a podmínku. Stačí mi "dospělé - 289,90 CZK".

**Comment by spalrobert** [comment]
Opravene
