### ISSUE TITLE
Obrázek Akce: Aktualizovat časový interval

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#4]
Časový inteval je nyní reprezentován přehledněji jako "začátek" a "konec" - je třeba podle toho upravit obrázek s akcemi.

**Comment by spalrobert** [comment]
fixed. ale fakt som upravil iba obrázok. nie je nutné upraviť nič iné?

**Comment by jakubklimek** [comment]
Příklad a specifikaci jsem upravoval já už dřív, takže by to mělo sedět. Vždy musí sedět obrázek, specifikace, schémata a příklady.

**Comment by jakubklimek** [comment]
Aha, koukám, že jste si u akcí zapomněli udělat pull request k sobě, takže pracujete se starou verzí, ne s tou co jsem upravil. Bacha na to.
