### ISSUE TITLE
Sportoviště: schéma - špatná reference u číselníků "typ sportoviště", "sport", "doplňkové služby""

### ISSUE THREAD

**Issue by jirkamarekbrno** [jirkamarekbrno/otevrene-formalni-normy#42]
@jakubklimek. Mohl by ses prosím tě na toto podívat, jak by to schéma mělo být. Teď jsem si uvědomil, že jsem to udělal špatně. Díky za koment. Jirka

**Comment by jakubklimek** [comment]
Nevim jestli dobře chápu dotaz. Pokud ty 3 věci mají být číselníky, pak v https://docs.google.com/spreadsheets/d/1y8OLRkO7tOD9eTVunXCMaqrj9ALYmsju chybí doplňkové služby. Zrovna ty bych ale viděl že by klidně mohly být prozatím opravdu textem, ne číselník.

Jinak na položky číselníku se odkazujeme pomocí IRI, viz #29, kde je pak vidět i jak to je v JSON Schématu:

```json
"jazyk": {
"$id": "#/items/properties/id",
"type": "string",
"format": "iri",
"title": "Jazykový identifikátor",
"description": "Dostupný jazyk v místě turistického objektu vycházející ze specifikace Evropského číselníku jazyků",
"examples": [
"https://op.europa.eu/cs/web/eu-vocabularies/at-concept/-/resource/authority/language/ARA/"
]
},
```

**Comment by jirkamarekbrno** [comment]
@jakubklimek super, toto jsem potřeboval vědět. díky. opraveno. Prosím o uzavření issue. J
