### ISSUE TITLE
Turistický cíl - jméno souboru schématu nemá diakritiku

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#44]
V `$id` je to správně, ale jméno souboru ne.
![image](https://user-images.githubusercontent.com/718827/69635157-142cd080-1054-11ea-89ea-5613ad824e88.png)

**Comment by jirkamarekbrno** [comment]
@jakubklimek opraveno. Prosím o uzavření issue. Díky.

**Comment by jakubklimek** [comment]
ještě detail - v tom `$id` je "aktuality"

**Comment by jakubklimek** [comment]
Teď je tam:
```
https://ofn.gov.cz/turistický-cíl/draft/schémata/turistický-cíl.json
```
Má tam být:
```
https://ofn.gov.cz/turistické-cíle/draft/schémata/turistický-cíl.json
```
