### ISSUE TITLE
Zkontrolovat, zda v jednoduchých příkladech jsou odkazy na JSON Schémata

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#46]
![image](https://user-images.githubusercontent.com/718827/69636717-80f59a00-1057-11ea-8104-7a52bccb9b2d.png)
![image](https://user-images.githubusercontent.com/718827/69636728-8521b780-1057-11ea-802d-8cc6e61e987c.png)

**Comment by spalrobert** [comment]
1e38a35 predošlý commit mal byť v #40

**Comment by jirkamarekbrno** [comment]
Zařazeno do úkolu s issues #55. Prosím o uzavření issue. Díky. J

**Comment by jakubklimek** [comment]
To se mi moc nelíbí, jelikož z #55 není jasné, co konkrétně je špatně a co se bude opravovat a jak - tedy to říká "nějak to celkově zlepšíme", což ale není issue - obsahuje to spoustu dílčích problémů, které pak nelze řešit a uzavírat samostatně.

**Comment by jakubklimek** [comment]
Tedy tuhle issue lze zavřít, až problém v ní popsaný bude v rámci #55 vyřešen, ne dřív.

**Comment by spalrobert** [comment]
@jirkamarekbrno @dvoriik akce, aktuality, otevírací doba a vstupné sú cajk

**Comment by jirkamarekbrno** [comment]
@jakubklimek zkontrolováno u všech. Doplněno u posledního kde nebylo - sportoviště. Díky za uzavření.
