### ISSUE TITLE
Akce: kolik má být hlavních sponzorů?

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#49]
V OFN Akce je hlavní sponzor vazba m:n - to moc nesedí s popiskem, kde se píše že to je nejdůležitější osoba. Tedy buď popisek upravit tak aby bylo jasné, že je jich více, nebo změnit obrázek a vše ostatní na n:1.

**Comment by spalrobert** [comment]
Malo to byť m:n pretože tých hlavných sponzorov môže byť viac ako 1... napríklad často majú akcie 2 hlavných sponzorov. Súhlasíš?

**Comment by jakubklimek** [comment]
Myslel jsem si to. Pak je třeba upravit ten popis.
