### ISSUE TITLE
Příklady vícejazyčných textů

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#50]
Tam, kde máme komplexní příklady a položky typu Text je třeba opravdu použít více jazyků (tedy cs, en, možná sk ;))

**Comment by jirkamarekbrno** [comment]
@jakubklimek rozumíme, doplníme všude. Máme jen otázku. Když v základní datovém typu je u textu definováno jen "cs" a "en", bude fungotvat i "sk" bez rozšířní základního datového typu? Díky moc.

**Comment by jakubklimek** [comment]
@jirkamarekbrno mělo by. JSON schéma kontroluje, zda tam je to co je předepsáno. Věci navíc tam být můžou vždy.

**Comment by spalrobert** [comment]
@jakubklimek ahoj. spravil som dvojjazyčnosť u OFN Akce, vstupné, aktuality a otevírací doba. prosím skontroluj to. Všimol som si ale že u otevírací doby je iba komplexný príklad. Myslím že by sa tam hodil aj minimalistický. Mám ho tam spraviť? Nie je ale lepšie počkať až na vykrištalizovanie OFN časová platnosť pretože otevírací doba je od nej vysoko závislá. Díky

**Comment by jakubklimek** [comment]
@spalrobert Ano, přidej ho tam. V minimalistické verzi otevírací doby by časová platnost vůbec nemusela být ne?
