### ISSUE TITLE
Vše: Konsolidace Brno OFN

### ISSUE THREAD

**Issue by jirkamarekbrno** [jirkamarekbrno/otevrene-formalni-normy#55]
V rámci této issue dojde ke konsolidaci OFN, co jsme vytvořili zatím jako tým. Bude se jednat o sjednocení obecně vyskytujících se věcí u každé ofn a sekundární kontrole specifikace a jsonů.

**Comment by dvoriik** [comment]
@jakubklimek v posledním commitu jsem odstranil zalomení \n v akcích a aktualitách.  Dnes se k tomu dostanu po 17:00, tak to neber za chybu (zvlášť pokud bude merge), bude odstraněno asap.

**Comment by jakubklimek** [comment]
Na toto není třeba mít "všeobjímající issue".
