### ISSUE TITLE
Časová platnost: vznik a ukončení

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#56]
Položky "vznik_časové_platnosti" a "ukončení_časové_platnosti" jsou jednak pojmenovány zbytečně dlouze, vždyť jsou na třídě "časová_platnost", ale hlavně je to nějaký zmatek. Ani ze specifikace není jasné, co to vlastně je. Je to od kdy do kdy ta specifikace platí? Proč je to modelováno jinak, než časová platnost samotná? Mně to přijde jako že by to měla být (pokud to opravdu potřebujeme)  časová platnost té časové platnosti, tedy rekurzivní vazba.

Mimochodem z PR zde:
![image](https://user-images.githubusercontent.com/718827/70303546-2ea73c80-1800-11ea-9d13-c348fd73743a.png)
je jasné, že ani vám není jasné jak to použít - specifikujete u akce platnost, která má pouze vznik a ukončení, tedy žádnou vlastní specifikaci.

**Comment by spalrobert** [comment]
ahoj @jakubklimek . dal som tam vznik_časové_platnosti a ukončení_časové_platnosti preto lebo sú to vlastnosti OFN časová platnost obdobně jako s ostatnými. Rozporuješ to ako vyzerá OFN časová platnost alebo to ako som to použil tu u akcí? Má to byť naviazané na OFN časová platnost vôbec? Ak hej tak nemôžem meniť a musím ísť podľa toho ako je to v OFN časová platnost definované. Akurát môžem pridať ďalšie položky ktoré sa v OFN časová platnost používajú ale pre naše účely stačí ten začiatok a koniec.

**Comment by jakubklimek** [comment]
@spalrobert Rozporuju obojí. Rozporuju, jak vypadá OFN časová platnost (jestli je potřeba a pokud ano, tak jak mít platnost platnosti) a taky to jak jste to pak použili v příkladech dalších OFN, viz screenshot (což může být tím, že to z OFN není jasné), protože říkáte, že je nějaká platnost (dále nespecifikovaná) platí od do... což nedává smysl.

**Comment by spalrobert** [comment]
Ok tak my musíme navrhnúť spolu nejaké riešenie a potom ti ho posunieme.

**Comment by jirkamarekbrno** [comment]
@jakubklimek prosím tě tou rekurzivní časovou platností myslíš to, že by OFN časová platnost měla v sobě ještě odkaz na OFN časová platnost? Tedy jako by vnořená časová platnost v časové platnosti? Děkuji za upřesnění. Já se nad tím ještě odpoledne zamyslím, protože si myslím, že časová platnost být má - jen je nutné ji přemodelovat. Jak to máme tak to s odstupem času nedává moc smysl.

**Comment by jakubklimek** [comment]
Jo, tak to myslim. V podstatě to modeluje to samy.

**Comment by spalrobert** [comment]
@jakubklimek u otevírací doby to upravím až keď bude známa nejaká stabilná verzia OFN časová platnosť.

**Comment by jirkamarekbrno** [comment]
@jakubklimek za mě je toto nyní ve stavu, kdy buď uzavřít a udělat nové issue na základě kontroly v rámci #55 nebo to dále komentovat již v té konsolidaci. Na co teď odkazuje toto issue, je už změněno/předěláno v rámci konsolidace.
