### ISSUE TITLE
Odkazy na jiné OFN musí být relativní

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#57]
Odkazy na jiné OFN musí být relativní, jinak se s dokumenty nedá pracovat lokálně (a je to obecně antipattern - co když bychom ofn přesunuli jinam - všechno se rozbije). 
Viz turistické cíle:
```
<a href="https://ofn.gov.cz/z%C3%A1kladn%C3%AD-datov%C3%A9-typy/draft/#mno%C5%BEstv%C3%AD">Množství</a>
```
1) když už absolutní odkaz, tak s diakritikou, nikoliv zakódovaný, tedy by to muselo být 
```
https://ofn.gov.cz/základní-datové-typy/draft/#množství
```
2) tady to má být relativní, tedy:
```
../../základní-datové-typy/draft/#množství
```

Mimochodem když jsem OFN dělal já, nedával jsem tam ani to /draft, aby to fungovalo i po vydání, kdy draft zanikne, a bude nahrazen konkrétní verzí. Nicméně konkrétní mechanizmus verzování OFN ještě není stanoven, takže zatím OK i s draftem, jen se na to později při vydávání musí myslet, tj. zda odkazovat na konkrétní či nejnovější verzi.

**Comment by dvoriik** [comment]
@jakubklimek má to být stejně i u schémat v JSON? Odkazy jsem upravil ...

**Comment by jakubklimek** [comment]
@dvoriik dobrý dotaz. Tam nejprve musime vyzkouset, ze to s relativnimi bude fungovat, pak ano, ale to nespěchá.

**Comment by dvoriik** [comment]
@jakubklimek můžeme to uzavřít nebo to dáme jako enhancement?

**Comment by jakubklimek** [comment]
Uzavírám. Relativní odkazy v JSON Schématech by dělaly problém při vývoji a validaci.
