### ISSUE TITLE
Sportoviště: JSON schéma v $id obsahuje "akce"

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#59]
```
https://ofn.gov.cz/akce/draft/schémata/sportoviště.json
```

**Comment by dvoriik** [comment]
opraveno v rámci #55, možno uzavřít

**Comment by jakubklimek** [comment]
Já to pořád opravené nevidím, viz https://github.com/jirkamarekbrno/otevrene-formalni-normy/blob/master/sportovi%C5%A1t%C4%9B/draft/sch%C3%A9mata/sportovi%C5%A1t%C4%9B.json#L3

**Comment by dvoriik** [comment]
pardon, chybka v týmové komunikaci :)
