### ISSUE TITLE
Otevírací doba: "od" a "do"

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#61]
Co je "od" a "do" na otevírací době? Pokud to má být časová platnost specifikace otevírací doby, pak by měla být použita OFN Časová platnost.

**Comment by spalrobert** [comment]
@jakubklimek ahoj. áno, má to byť tak ako píšeš. Toto upravim až keď ale bude známa nejaká ucelená verzia OFN časovej platnosti. Včera sme sa s tým bavili a myslím že je tam ešte kopec nejasností.

**Comment by spalrobert** [comment]
Tento posledný commit je  že som zatiaľ opravil aspoň json príklad aby bol validný aj so schématom. Samozrejme bude nutné opraviť podľa ofn časová platnosť.

**Comment by jakubklimek** [comment]
@spalrobert ten https://github.com/jirkamarekbrno/otevrene-formalni-normy/commit/c78a960bafcde5e921b8448c770c30c942fb031f ale neni dobře. Teď tam máš čas, který má 2 začátky a 2 konce. Musí to být 2 časy, který má každý 1 začátek a 1 konec.

**Comment by spalrobert** [comment]
Je to takto dobre? schema validator to sčekoval že ok. Mám ale otázku...  vazba sa volá čas ale v jsone som tomu dal názov entity - Časový interval... ponevadž názov entity bol aj položke Den v týdnu a nie vazba Den ... je to ďalej pod platnosťou v tom jsone. Alebo som to mal nazvať čas a potom vo vnútri toho zoznamu som to mal nazvať časová platnosť? Teda presne naopak ako je to teraz? Keď som to totižto spravil takto tak mi napísalo že očakáva objekt ale dostal array.  Problém je že neviem ako z toho spravím objekt... ja predsa potrebujem aby to bol array tak aby ten jeden den mal začiatok a koniec nie? Šťastné a veselé!

**Comment by spalrobert** [comment]
Táto otevírací doba je trocha komplikovanejšia kvôli tomu že chýba stabilná verzia OFN časová platnosť... ak by bola totižto hotová tak potom by sa asi zmenila logika tejto OFN kompletne. Zatial som časový interval zmenil na časovú platnosť... commity dole... ale nie je to konzistentné s od a do. Bude nutné opraviť ako schéma tak príklady ale zatiaľ sa viac asi neviem pohnúť. Rovnaký problém je u vstupného a na tie potom naväzujú sportovište, turistický cíl a akce.

**Comment by jakubklimek** [comment]
@spalrobert 

1. Den v týdnu už má být dle publikovaného číselníku
2. Pořád říkám, že ta časová platnost v řadě OFN není klíčová, tedy minimálně minimálních příkladů se netýká. V otevírací době zatím minimální příklad není, ale měl by být
3. Co se týče názvů v JSONu, musí být stejné, jako v sekci Specifikace, položka Vlastnost nebo Vazba. Ty jsou zpravidla pojmenovány podle té vazby, nikoliv podle té cílové entity - vazba dává ten význam, ve kterém je cílové entita použita.
4. Problém s validací by chtěl lépe popsat, takhle mi není jasné co přesně je za problém, nicméně ten aktuální příklad je divně. Máš tam časový interval, který vede na pole s jedním prvkem, a pak další časový interval, který zase vede na pole s jedním prvkem. Navíc ty prvky jsou stejné - není jasné, proč je to 2x. Nicméně ten interval (jeden prvek) má začátek a konec - to je jeden objekt. K tomu žádný array potřeba není.
5. Aktuálně z OFN není jasné, co to od a do má vlastně znamenat, takže je těžké se bavit o konzistenci s jinou OFN. Podle schema.org by od a do měly být časy kdy je dané dny otevřeno (tedy ne platnosti ani intervaly) a pak den je vazba na pole dní, kdy tato otvíračka platí. Pak toto celé může mít vazbu na Platnost, která řekne, že to takhle ale platí jen o prázdninách, nebo jenom v lednu atd...

**Comment by spalrobert** [comment]
@jakubklimek 1. den v týdnu je už špecifikovaný dle číselníku... rovnako sú spravené aj ostatné číselníky u ostatných ofn - nie som si ale istý že to je v príkladoch správne... prosím sčekni.
2. Minimálny príklad som tam pridal ale odstránil som iba popis pretože mi vôbec nie je jasné ako môžeme spraviť minimálny príklad bez časovej platnosti... min. príklad u otevíracej doby bez časovej platnosti nedáva zmysel nie? 
3. a 4. asi nemá zmysel riešiť bez toho aby bolo jasné ako otevírací doba bude vyzerať. Viď bod 5.
5. Zmenil som logiku podľa toho čo si písal... 
Pozri a prosím napíš koment k tomu:
https://drive.google.com/file/d/1Ojz-CFxJnV_ZMlA5jgcSOnmkNdRYOxP9/view?usp=sharing

Od a do som odčlenil na vazbu aby mohlo byť k otváracej dobe priradených viacero časov - napr. 10:00 až 12:00 a 14:00 až 16:00. Od aj do by boli časový okamžik teda iba? V situácii že má zariadenie každý deň iné otváracie doby dajme tomu ... teda 7x za týždeň by bolo potom teda vytvorených 7 otváracích dôb. Tak by to malo fungovať. Sedí?  

Ak by ale bola ofn časová platnosť tak potom, by sme ale nemusel predsa použiť ani dny a ani čas a ani platnost iba by som sa odkázal na ofn časová platnosť nie? Alebo by to tak nemohlo fungovať? 

PS. Krásny nový rok. Ospravedlňuje sa za neskoršiu odozvu bol som mimo až do 5teho. Už budem pravidelne komunikovať.

**Comment by jakubklimek** [comment]
@spalrobert 
1. není to správně. Má to být pole iri, ne pole objektů, které mají "iri":
```json
"den": [
"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/pondělí",
"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/úterý",
"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/středa"
   ]
```
2. Pak si asi nerozumíme v tom, jakou roli má časová platnost v otevírací době. Což je celý point této issue. Moje představa minimalistického příkladu: Obchod má otevírací dobu Pondělí - Pátek. 8:00-16:00. To by mělo vypadat takto:
```json
{
    "od": "08:00:00",
    "do": "16:00:00",
    "den": [
        "https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/pondělí",
        "https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/úterý",
        "https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/středa",
        "https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/čtvrtek",
        "https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/pátek"
    ] 
}
```
Proto si myslím že `od` a `do` mají být časy, nikoliv platnosti.
Roli časové platnosti vidím pouze v tom, že se řekne, že tato specifikace otevírací doby platí jen v zimě, a pak to bude něco jako:
```json
{
	"název": {
		"cs": "Zima",
		"en": "Winter"
	},
	"od": "08:00:00",
	"do": "16:00:00",
	"den": [
		"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/pondělí",
		"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/úterý",
		"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/středa",
		"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/čtvrtek",
		"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/pátek",
	],
	"platnost": {
		...specifikace zimy dle OFN Časová platnost
	}
}
```
 Zbytek konverzace se od tohoto už odvíjí, včetně obrázku.

Jen pro úplnost, jak se (inspirace ve schema.org) řeší trochu složitější otevírací doby - dopoledne a odpoledne:
```
```json
[{
	"od": "08:00:00",
	"do": "12:00:00",
	"den": [
		"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/pondělí",
		"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/úterý",
		"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/středa",
		"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/čtvrtek",
		"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/pátek"
	]
}, {
	"od": "13:00:00",
	"do": "16:00:00",
	"den": [
		"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/pondělí",
		"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/úterý",
		"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/středa",
		"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/čtvrtek",
		"https://data.mvcr.gov.cz/zdroj/číselníky/dny-v-týdnu/položky/pátek"
	]
}]
```

**Comment by spalrobert** [comment]
@jakubklimek ahoj, tak som to prerobil, prosím pozri sa na to. Jediný menší zádrhel je že mi pri validácii jsonu so schémou stále píše že ten číselník den v týdnu je array a on čakal string.... rovnako ako v otevíracej dobe je to ale riešené aj v ostatných ofn tak to budem musieť zmeniť aj u nich. Skúsim na to prísť cez víkend ako to správne zapísať.   Ostatné by malo byť v cajku.

**Comment by jakubklimek** [comment]
@spalrobert to jsem řešil s @jirkamarekbrno - měl by ti to vysvětlit. Ten "den" máš teď v JSON schématu zadefinován opravdu jako string. Mělo by to být pole těchto stringů. Pak je to špatně i v JSON příkladu, kde to zas máš jako pole s jedním objektem, který má spoustu klíčů "iri". Podívej se znovu na https://github.com/jirkamarekbrno/otevrene-formalni-normy/issues/61#issuecomment-571967543

**Comment by jakubklimek** [comment]
@spalrobert taky ty otevírací časy jsem právě myslel, že oddělovat nebudeme, viz https://github.com/jirkamarekbrno/otevrene-formalni-normy/issues/61#issuecomment-571967543 - takto zavádíme další možnost jak specifikovat kombinaci otevíracích dob, což mi přijde zbytečné. Tedy bych nechal od a do na otevírací době, ne zvlášť s vazbou m:n.

**Comment by spalrobert** [comment]
opravené... a asi tomu už chápem... ale aj tak sa rád o tom pobavím keď sa strentneme. Krásny víkend.

**Comment by jakubklimek** [comment]
@spalrobert Teď je "od" a "do" časový okamžik, měl by to být ale čas - časový okamžik může být i datum, což by nedávalo smysl.

**Comment by spalrobert** [comment]
Prepáč... moja chyba. Html som už upravil(zatiaľ u seba) ale kde zoženiem json schéma? Našiel som XML schéma v základných datových typoch... môžem použiť to.. asi nie však. Môžem použiť schéma pre časový okamžik... to asi tiež nie však. Díky

**Comment by jakubklimek** [comment]
@spalrobert Z [JSON schématu pro časový okamžik](https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-okamžik.json) se můžeš inspirovat, jak má vypadat čas. Je to už jednoduchá hodnota, tedy se definuje přímo, ne odkazem na jiné schéma.

**Comment by jakubklimek** [comment]
@spalrobert Ve specifikaci je link správně, ale jeho text je pořád Časový okamžik
