### ISSUE TITLE
Dodělat odkazy na metadata NKOD do sekce č. 5 v každé HTML

### ISSUE THREAD

**Issue by jirkamarekbrno** [jirkamarekbrno/otevrene-formalni-normy#62]

**Comment by jakubklimek** [comment]
@dvoriik Soubory s metadaty jsou pojmenovány divně.
1) Má to být něco.jsonld.txt, tedy místo `nkod-registrace.jsonld_otevírací_doba.txt` `otevírací_doba.jsonld.txt`
2) Má to samozřejmě smysl jen u OFN pro konkrétní datové sady, nikoliv o "pomocné". Samotnou otevírací dobu nikdo zveřejňovat v NKOD nebude. Naopak Akce ano.

**Comment by dvoriik** [comment]
@jakubklimek názvy jsem upravil (takto se to automaticky stáhlo z reg. formuláře - neupravoval sem to) ...otázka: Může to u těch pomocných (tzn. vstupné, doba, platnost) zůstat nebo je to chyba a z html smazat? Díky

**Comment by jakubklimek** [comment]
@dvoriik
1) Z pomocných je třeba to odstranit (z HTML i GitHubu - prostě kompletně) - nedává to tam žádný smysl - proč by to tam mělo být?

2) přejmenováno je to špatně - teď vše končí `.jsonld.txt.txt` místo `.jsonld.txt`. Nepojmenováváš soubory náhodou v Průzkumníkovi Windows a nemáš vypnuté zobrazování přípon souborů?

> (takto se to automaticky stáhlo z reg. formuláře - neupravoval sem to)

Upravoval, jinak by se do `nkod-registrace.jsonld_otevírací_doba.txt` těžko dostala ta otevírací doba.

**Comment by dvoriik** [comment]
@jakubklimek > 2\. přejmenováno je to špatně - teď vše končí `.jsonld.txt.txt` místo `.jsonld.txt`. Nepojmenováváš soubory náhodou v Průzkumníkovi Windows a nemáš vypnuté zobrazování přípon souborů?
> 
> >
ano, to byl ten problém ...
Z pomocných odstraněno (zmátl mě trochu název issue-dodělat u všech html) a ta registrace se rovněž dělala u všech ofn, tak proto. 
Snad v pořádku ...
