### ISSUE TITLE
Otevírací doba: Přidat minimalistický příklad

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#64]
@spalrobert Ano, přidej ho tam. V minimalistické verzi otevírací doby by časová platnost vůbec nemusela být ne? Ostatně teď není ani v komplexní, takže to na tom není závislé.

_Originally posted by @jakubklimek in https://github.com/jirkamarekbrno/otevrene-formalni-normy/issues/50#issuecomment-566008949_

**Comment by spalrobert** [comment]
nezrušíme tento issue a nepresunieme to pod issue #61 ? Tam som riešil aj minimalistický príklad...

**Comment by jakubklimek** [comment]
Nepřesouval bych, až bude minimalistický příklad v pořádku, toto uzavřeme. Teď tam ještě je chybička v názvu sekce jednoduchého příkladu chybí to "jednoduché".

**Comment by jakubklimek** [comment]
Aha, už je :)
