### ISSUE TITLE
Turistické cíle: Typ turistického cíle: nekonzistence - spousta věcí

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#69]
Jak to má být s typem turistického cíle? Bude to číselník, nebo textová hodnota? [Číselník](https://data.gov.cz/datová-sada?iri=https://data.gov.cz/zdroj/datové-sady/MV/706529437/27bfee55f8eb2ace99e322a04f1f3712) pro to máme, takže předpokládám, že to bude číselník.
- Pak tomu neodpovídá obrázek:
![image](https://user-images.githubusercontent.com/718827/71669598-7f617500-2d6d-11ea-9c59-c91c5678cf55.png)
- Ve specifikaci je název vazby 'typ_turistického_cíle' - zde bych byl pro 'typ', jelikož je to vazba z entity typu turistický cíl...
- Ve [specifikaci entity](https://ofn.gov.cz/turistické-cíle/draft/#třída-typ-turistického-cíle) je typ `řetězec` s malým `ř`
- V JSON schématu je vazba `typ turistického cíle` bez podtržítek a s typem Text

Předpokládám tedy, že to bude vyřešeno v rámci přechodu na číselník.

**Comment by dvoriik** [comment]
@jakubklimek možno uzavřít, či?

**Comment by jakubklimek** [comment]
Ještě bych opravil kardinalitu u Typu turistického cíle - je tam 1, to znamená že by to bylo povinné. Tomu se v OFN snažíme vyhnout, čili 0..1

**Comment by jakubklimek** [comment]
A není konzistentní specifikace, kde je správně `typ` a JSON a JSON schéma

**Comment by jakubklimek** [comment]
@dvoriik Stále není konzistentní `typ` - v JSONu je `typ_turistických_cílů".

v obrázku je pak povinné (1) u provozovatele, umístění, bezbariérovosti. To by mělo být 0..1 pokud chceme říct, že max 1, nebo 0..n pokud chceme říct že až n.
