### ISSUE TITLE
Aktuality: název a popis bude Text, ne řetězec - kvůli vícejazyčnosti

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#7]

**Comment by spalrobert** [comment]
fixed. Ale zmenil som teda odkazovanie z základní-datové-typy/#řetězec na ...základní-datové-typy/draft/schémata/text.json

Správne?

**Comment by jakubklimek** [comment]
Ne. Odkaz ze specifikace má vést na specifikaci, na JSON Schéma se odkazuje JSON Schéma. Čili to má být základní-datové-typy/draft/#text

**Comment by jakubklimek** [comment]
@spalrobert https://github.com/jirkamarekbrno/otevrene-formalni-normy/commit/953ad982574b53322f51e3938a6a7aab11e03075 tam máš pořád /schémata ... má to vést do toho HTML dokumentu, podívej se, jak je to v jiných OFN.
