### ISSUE TITLE
JSON: vytvořit u každé OFN schéma pro jeden objekt a pro pole (více objektů)

### ISSUE THREAD

**Issue by jirkamarekbrno** [jirkamarekbrno/otevrene-formalni-normy#70]

**Comment by jakubklimek** [comment]
Obecně jde o to vždy vědět, zda se odkazuji na jeden objekt nebo pole objektů. Pole se dá definovat jak na straně referencujícího, tak na straně referencovaného schématu. Někde dává smysl mít přímo v OFN definováno, že se vždy bude jednat o pole (seznam akcí). Pak se ale může stát, že nějaká jiná OFN bude chtít odkázat na akci, ale jen na jednu, ne na pole. Proto se zde hodí mít JSON schéma jak pro jednu akci (typ objekt), tak pro seznam akcí (typ pole referencující jednu akci).

Ne všude to ale takto musí dávat smysl.
