### ISSUE TITLE
Vše: Obrázky předělat to lidsky čitelné podoby

### ISSUE THREAD

**Issue by jirkamarekbrno** [jirkamarekbrno/otevrene-formalni-normy#71]
Obrázky by měli obsahovat "lidsky čitelné texty", tedy bez "podtržítek mezi lower case". Ve specifikaci poté už bude v sekci typ ta strojová čitelnost.

**Comment by dvoriik** [comment]
Obrázky upraveny vyjma Parlamentních dat. Psal jsem michalovi skopovi, zatím bez reakce

**Comment by dvoriik** [comment]
@jakubklimek Obrázky upraveny, zatím stále bez reakce od Michala Škopa. Vyřešíme na společném meetingu.
