### ISSUE TITLE
Vztah mezi akcemi a aktualitami a číselník Témata událostí

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#73]
1. Neměla by aktualita odkazovat také na Akci?
2. Neměla by mít akce také link na číselník "témata událostí"?

**Comment by dvoriik** [comment]
@jakubklimek ad 1) nesouhlasíme s propojením aktualit a akcí, protože akci odkazuješ na aktualitu skrze URL akce. Samostatná akce není aktualitou. 
ad 2) Spíše než číselník "témata událostí" bychom udělali "témata akcí", který se od událostí značně liší (sportovní, hudební, cestovatelské, apod.). To události nepokrývají zcela. EU voc slovník nenabízí event type či něco podobného, takže by jej asi bylo třeba vytvořit. Navrhujeme to udělat ve spolupráci s Czech Tourism, jak by měla být ta spolupráce. Souhlas?

**Comment by jakubklimek** [comment]
@dvoriik 
1) nevim jestli si rozumime. Nemluvil jsem o sloučení OFN, ale zahrnutí vazby z Aktuality na Akci. Tu tam nevidím a dávalo by mi smysl v aktualitě mluvit o akci. Pokud myslíš že se to dá udělat přes url Přílohy, tak to z toho nikdo nepozná. Proto bych to specifikoval jako extra vazbu. Jinak asi nerozumim tomu "protože akci odkazuješ na aktualitu skrze URL akce.".
2) není každá akce událost? Tj. nemělo by téma akcí být podmnožinou obecnějšího tématu události? Jinak ano, do těchto čísleníků určitě zahrneme položky z jiných zdrojů.

**Comment by jirkamarekbrno** [comment]
ad 1) Nerozumíme si. My jsme mysleli, že když máš aktualitu, tak na akci v rámci této aktuality odkázeš pomocí iri dané akce. Tedy pokud bychom dali vazbu v akcích na aktuality, tak to potom můžeme dát vazby v aktualitách např. na sportoviště apod. Myslíme tím, že by měla být zachována jednotka: "akce" a jednotka "aktuality" samostatně. Neděláme pro uživatele mapu toho, kde všude se to pojí, ale popisujeme právě ty jednotlivé celky. Tedy akce může být s aktualitou i bez a tím, když tam dáme do akcí aktualitu, tak jakoby říkáme, je vhodné vždy o akci aktualitu napsat, což není podle nás vždy pravda.

ad 2) uvědomili jsme si, že motáme dva pojmy, "typ akce" a "téma události". Dále ve stávajícím číselníku událostí je jedna položka event "nadcházející událost", tak to nedává smysl podle nás pro akce, ale to je drobnost. Témata by se tedy k akci hodila (i když si myslím, že se tak nepoužívají), ale stejně tak by se hodil typ akce (koncert, divadlo apod.). To by měl být dle našeho nový číselník. Myslíš to tak?

**Comment by jakubklimek** [comment]
ad 1) V OFN říkáme "pokud tato data máte, tak je uvádějte takto". Tzn. když tam teď nic není, a někdo by k aktualitě měl i akci, tak neříkáme, jak se na ní má odkázat. Ty říkáš "pomocí IRI" - OK, ale v jakém klíči? `odkaz_na_akci`, `akce`, `???`? Takže my bychom právě měli ukázat, jak to propojit, pokud je co propojovat. Vede to ale na něco, co jsme zatím v OFN viděli jen u číselníků. Zatím jsme měli to, že máme vazbu na jinou OFN jako třeba na Umístění, která znamená "a tady bude objekt, který se modeluje dle OFN ...". U číselníků je to ale jinak, tam to říká "A tady bude IRI položky z jiné datové sady". A to je tedy to, co chceme říct u Aktualit. "Tady bude IRI akce, pokud jí máte v jiné datové sadě. Tedy na akci se odkažte, nevkládejte ji sem v plné podobě". To můžeme pořešit tím, že typ takové položky bude specifikováno nikoliv jako Akce, ale jako IRI a v popisu bude, že to je IRI akce (odkaz na OFN Akce) - podobně jako u číselníků.

ad 2) ano, tak jsem to myslel. Jsou to 2 různé číselníky, s tím, že to téma se hodí jak k akci, tak k aktualitě
