### ISSUE TITLE
Vazby v diagramu psát s "0.." - je to přesnější. Tedy "0..1" či "0..n"

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#78]

**Comment by spalrobert** [comment]
Ahoj @jakubklimek  Chcem sa spýtať na upresnenie.... nie všade to mám zmeniť však? Napríklad u vstupného ak by s vazbou na částku bolo namiesto súčastnej 1 novo 0..1, tak by to znamenalo že vstupné nemusí mať částku, čož je ale blbosť. Částka tam musí byť inak to vstupné nemá zmysel. Mám preto obdobne postupovať aj u ostatných ofn a nie to iba všetko prepísať do nového formátu? Skrátka zamyslieť sa nad tým aby to dávalo zmysel a u niektorých vazieb teda zostane popis vazby tak ako je tam už teraz.. teda bez 0.. Idem na to dobre? Díky a krásny víkend.

**Comment by jakubklimek** [comment]
Sportoviště to tak stále nemají.
