### ISSUE TITLE
Linky na číselníky v NKOD nevedou na datovou sadu

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#79]
vede místo toho na všechny datové sady MV ČR

**Comment by jakubklimek** [comment]
Například Aktuality, Sportoviště

**Comment by dvoriik** [comment]
@jakubklimek ano, to bylo schválně. Ve specifikaci Typ vede sem: https://data.gov.cz/datov%C3%A1-sada?iri=https://data.gov.cz/zdroj/datov%C3%A9-sady/MV/706529437/b2ff01ed40020b24ec78425f9fd924cc

a dále v Popisu je https://data.mvcr.gov.cz/zdroj/datov%C3%A9-sady/%C4%8D%C3%ADseln%C3%ADky/t%C3%A9mata-ud%C3%A1lost%C3%AD
který odkazuje do všech sad publikovaných MV ČR v NKOD https://data.gov.cz/datov%C3%A9-sady?poskytovatel=Ministerstvo%20vnitra

Takto je to u všech číselníků. Prosím tedy o vyjádření.

**Comment by jakubklimek** [comment]
@dvoriik No přijde mi to divný :).
![image](https://user-images.githubusercontent.com/718827/74435169-27398a80-4e64-11ea-89bf-1c4f2a5df292.png)
Odkaz z Téma aktuality vede na https://data.gov.cz/datová-sada?iri=https://data.gov.cz/zdroj/datové-sady/MV/706529437/b2ff01ed40020b24ec78425f9fd924cc To je OK, ale stejný odkaz bych čekal i z "číselník v Národním katalogu otevřených dat" - dávat tam odkaz na všechny datové sady MV ČR nedává žádný smysl.
