### ISSUE TITLE
Aktuality: Zveřejněno (a relevantní_do): Nemá to být "Datum a čas"?

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#8]
Zveřejnění aktuality typicky probíhá v i v nějakém čase. Máme 2 možnosti:
1) říct, že to vždy bude [datum a čas](https://ofn.gov.cz/základní-datové-typy/draft/#datum-a-čas)
2) říct, že přesnost dopředu nevíme, a za cenu mírného zesložitění formátu použít typ ze základních datových typů: [Časový okamžik](https://ofn.gov.cz/základní-datové-typy/draft/#časový-okamžik)

**Comment by spalrobert** [comment]
No tu je to na diskusiu. My sme pozerali viacero aktualít ktoré mestá a obce produkujú a vždy tam uvádzajú iba dátum kedy aktualita vyšla... preto som ho tam dal. Otázka je akú relevanciu by mal čas zverejnenie keď aktualitu produkuje samospráva? Nie je jedno či aktualitu zverejnili ráno o 8:00 alebo o 15:00? Aktualita je aktívna od dátumu zverejnenia po dátum expirácie a preto mi tam moc čas pri obciach nedáva zmysel. Ale napr. noviny pracujú v inom režime ako obce - tie tak zverejňujú aktuality aj s časom. Mám tam teda dať ten čas? Je to OFN pre obce ale máme to robiť aj tak aby to mohol používať súkromný sektor?

**Comment by jakubklimek** [comment]
Co když má město 2 aktuality za den? Pak zobrazení jejich pořadí řídí čas, který by nebyl zachycen. Tedy jsem pro to změnit na Časový okamžik, ať tam pak každý může dávat to co má. S tím zda je to obec nebo soukromý sektor to nesouvisí.

**Comment by spalrobert** [comment]
fixed. ale v json schématu som nič neupravoval tak nie som si istý či je to dobre.

**Comment by jakubklimek** [comment]
No neni. Je potřeba upravit

- [x] Popis ve specifikaci, aby se tam neříkalo Datum a čas, ale Časový okamžik
- [x] JSON Schéma
- [x] JSON Příklad
- [x] Obrázek - tady bych to výjimečně nechal. Časový okamžik je sice entita, ale obrázek má být hlavně pro představu, a to to splňuje i takto. Ve specifikaci a příkladu se pak člověk dozví, jak to je ve skutečnosti.

**Comment by jakubklimek** [comment]
@spalrobert  V JSON příkladu v HTML dokumentu to je stále postaru, v JSON příkladu ke stažení taky

**Comment by spalrobert** [comment]
Nerozumiem... v príklade som to menil a zmenil som to podľa základného datového typu časový okamžik: datum a čas: 2019-01-01T09:30:00 a v príklade je to predsa 2019-09-27T09:30:00

**Comment by jakubklimek** [comment]
To je ale konceptuální příklad ve specifikaci - nezávislý na konkrétním formátu. V JSONu viz https://ofn.gov.cz/základní-datové-typy/draft/#example-46-casovy-okamzik-datum-v-json - mělo by to tedy být:
```json
"zveřejněno": {
    "datum_a_čas": "2019-01-01T09:30:00"
}
```
stejně tak relevantní do.

**Comment by spalrobert** [comment]
Aha, ďakujem. Opravené. Nemalo by sa to ale opraviť aj v schématu? V schématu je to totižto tak ako to bolo v príklade.  Či v schématu to môže byť tak? Díky

**Comment by jakubklimek** [comment]
@spalrobert Teď je to opravené jen v komplexním případě. V jednoduchém je to stále špatně. 

> Nemalo by sa to ale opraviť aj v schématu? V schématu je to totižto tak ako to bolo v príklade. 

Ano, jak jsem psal v https://github.com/jirkamarekbrno/otevrene-formalni-normy/issues/8#issuecomment-543169047, musí to být synchronizované i s JSON schématem, na které mimochodem z jednoduchého příkladu chybí link. Nicméně já to v tom schématu vidím dobře, 
```json
"zveřejněno": {
"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-okamžik.json"
},
"relevantní_do": {
"$ref": "https://ofn.gov.cz/základní-datové-typy/draft/schémata/časový-okamžik.json"
},
```
jen to předtím nebylo validní.

A ještě příklady prožeň skrz https://jsonlint.com/ a v HTML pak nahrazuj tabulátory mezerami, ať to nějak vypadá.

**Comment by jirkamarekbrno** [comment]
@spalrobert je to tedy hotovo toto?

**Comment by spalrobert** [comment]
@jirkamarekbrno @jakubklimek  no malo by byť

**Comment by jakubklimek** [comment]
Ještě ten příklad není upraven v HTML

**Comment by jakubklimek** [comment]
@spalrobert Kdybych chtel prudit, tak reknu ze to jeste neni spravne formatovany (indentovany) v html. Nicmene ten priklad se asi jeste bude menit, tak to nechme na priste ;)
