### ISSUE TITLE
Aktuality: Téma je v príkladu pouze jedno a není to pole

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#80]
Téma je v obrázku vazba m:n. V JSONu to je ale jedna hodnota. Mělo by to být tedy pole s jedním IRI.

**Comment by jakubklimek** [comment]
Teď je ale samozřejmě ještě třeba příslušně upravit JSON Schéma, protože teď je tam pole stringů a ne string.

**Comment by dvoriik** [comment]
@jakubklimek můžeš mi to prosím vysvětlit? Popravdě nevím, jak mám pole v json schema odstranit, aby to bylo validní. Vlastně původní json s json schema bylo v json schmea validator obojí správně. Tedy tomu moc nerozumím. Díky

**Comment by jakubklimek** [comment]
@dvoriik Teď je tam:
```json
"téma": {
	"id": "#/items/properties/téma",
	"type": "string",
	"format": "iri",
	"title": "Téma aktuality",
	"examples": [
		"https://data.mvcr.gov.cz/zdroj/číselníky/témata-událostí/položky/doprava"
	]
}
```

Tedy téma je definováno jako string s IRI. Má to ale být pole těchto stringů s IRI:
```json
"téma": {
	"type": "array",
	"items": {
			"id": "#/items/properties/téma/items",
			"type": "string",
			"format": "iri",
			"title": "Téma aktuality",
			"examples": [
				"https://data.mvcr.gov.cz/zdroj/číselníky/témata-událostí/položky/doprava"
			]
		}
}
```
