### ISSUE TITLE
Časová platnost: "Opakovatelnost" => "Opakování"

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#85]
Nebylo by jednodušší říkat "Opakování" než "Opakovatelnost"?

**Comment by dvoriik** [comment]
Ahoj, myslíme si, že by to měla být opakovatelnost viz např: https://cs.glosbe.com/cs/cs/opakovatelnost nebo http://ach.upol.cz/user-files/intranet/02a-terminologievim3-1287047120.pdf. Tedy toto navrhujeme ponechat + časová platnos ta časová opakovatelnost zní dohromady lépe než platnost a opakování. ok?

**Comment by jakubklimek** [comment]
Já teda stále přesvědčen nejsem. I z těch linků vyplývá, že opakovatelnost je "schopnost něco opakovat, míra, do jaké je něco opakovatelné / míra, s jakou je něco možné zopakovat". To je něco jiného než specifikace, jak často se něco opakuje, což je to, co je v OFN. Tj. teprve tehdy, když je něco opakovatelné, tak můžeme řešit, jak se to opakuje.

Pokud se něco opakuje, řekl bych, že tím pádem je to opakovatelné (jde to opakovat). Ale to, jak často se to opakuje, bych opakovatelností nenazýval.

**Comment by jirkamarekbrno** [comment]
@jakubklimek navrhujeme toto řešení: vazbu změnit na "opakování" ale tu entitu nechat "časová opakovatelnost". Souhlas?:)

**Comment by jirkamarekbrno** [comment]
Jo a další otázka, nemáme už rozdělit tu časovou platnost a časovou opakovatelnost na dvě OFN, protože třeba u kontejnerů potřebuješ odkazovat na oboje zvlášť.

**Comment by jakubklimek** [comment]
@jirkamarekbrno OK, tak aspoň tu vazbu no ;)

Co se týče rozdělení - to je estetická věc. Funkčně se teď můžeme odkudkoliv odkazovat na entitu opakovatelnost, i když je v jiné OFN. V tomhle případě bych ale byl pro, tedy rozdělit.
