### ISSUE TITLE
Časová platnost, příklad 7: dny v měsíci mají být čísla, tedy 1 místo "1"

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#87]

**Comment by jirkamarekbrno** [comment]
Hotovo, prosím @jakubklimek o uzavření:). Díky. J

**Comment by jakubklimek** [comment]
Není hotovo, příklad není validní (`10"`). Také je špatně ID sekce sedmého příkladu (je tam šestý).
