### ISSUE TITLE
Příklady musí být strojově čitelné, nikoliv lidsky čitelné

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#88]
Např. [časová opakovatelnost](https://ofn.gov.cz/časová-platnost/draft/schémata/časová-opakovatelnost.json) má v "examples" pro číslo `"20. minuta"` místo `20`.

**Comment by jirkamarekbrno** [comment]
Ahoj, ta první oprava byla špatně, vrátil jsem to zpět tou opravou zpět. Oprava 2 opravila, co měla. Prosím o uzavření @jakubklimek . Díky. J

**Comment by jakubklimek** [comment]
Ahoj, pořád vidím stejný problém, viz https://ofn.gov.cz/časová-platnost/draft/#vlastnost-specifická-frekvence-minuta apod.

**Comment by jirkamarekbrno** [comment]
@jakubklimek počkat, v JSON schématu je to opraveno, ale index.html má být přece lidsky čitelný ne? stejně u OFN Tur. cílů v kapacitě. Nespletl ses?

**Comment by jakubklimek** [comment]
@jirkamarekbrno Aha, už chápu kde je problém. Do názvu issue jsem dal specificky JSON Schéma. Ano, index.html je lidsky čitelný dokument. Ale v sekci specifikace ty Příklady (v html <code>) už jsou tak, jak budou v datech - třeba IRI nebo číslo. Nemyslím si, že by byl některý takový příklad těžko interpretovatelný. Pokud ano, můžeme pořešit zvlášť.

**Comment by jakubklimek** [comment]
Je tady problém i s příklady v JSON Schématu - teď jsou definovány jako řetězce `"2"`, nikoliv jako čísla `2`.
