### ISSUE TITLE
Časová platnost: Otevřený interval je třeba specifikovat explicitně

### ISSUE THREAD

**Issue by jakubklimek** [jirkamarekbrno/otevrene-formalni-normy#89]
[Příklad 6](https://ofn.gov.cz/časová-platnost/draft/#příklady-časová-platnost-šestý-příklad) má říkat, že se jedná o interval "do odvolání", tedy že nemá konec. To by se mělo vyjádřit explicitně, ne tím že bude chybět konec.

To ale platí pro intervaly obecně. Přemýšlím tedy, že by součástí definice [Časového okamžiku](https://ofn.gov.cz/základní-datové-typy/draft/#časový-okamžik) bylo `"nespecifikováno": true`

**Comment by jirkamarekbrno** [comment]
Ahoj @jakubklimek , přemýšleli jsme nad tím s borcama a souhlasíme s tou úpravou časového okamžiku. Máme to udělat my nebo to udělaš ty? Díky:).

J
